# Generated by Django 6.0.2 on 2026-02-09 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the challenger', max_length=100)),
                ('section', models.CharField(help_text='Student year and section', max_length=50)),
                ('speed_score', models.PositiveIntegerField(help_text='Typing net speed in Words Per Minute (WPM)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the challenge was taken')),
                ('entered_by', models.ForeignKey(help_text='ICT staff who entered this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typed_challengers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typing Challenger',
                'verbose_name_plural': 'Typing Challengers',
                'ordering': ['-speed_score', 'created_at'],
            },
        ),
    ]
