# Generated by Django 6.0.2 on 2026-02-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingSprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='challenger_photos/'),
        ),
    ]
